#!/usr/bin/env python

Import("env")

env_mysqlcppconn = env.Clone()


if env["platform"] in ["linuxbsd", "linux", "bsd", "x11", "server"]:
	env_mysqlcppconn.Append(LIBPATH=["/usr/lib"])	# Path to libraries

env_mysqlcppconn.add_source_files(env.modules_sources, "*.cpp")

env.Append(LIBS=["mysqlcppconn"])









